### ISSUE TITLE
Change the way you set up your environment

### ISSUE THREAD

**Issue by jmkd3v** [MenacingMecha/MenacingMecha.github.io#1]
Hello! 

Instead of your current solution - compiling *before* committing to GitHub and leaving your raw scss on your PC, you should consider placing the source in the `main` branch and then placing the compiled materials in a separate `gh-pages` branch. This allows others to contribute to your website! 

I was planning on creating a pull request but I am unable to properly do so without raw sources.

Thank you!

**Comment by MenacingMecha** [comment]
Thank you for taking an interest, but could I first inquire as to the nature of the pull request? As this is a repo for a personal portfolio website, the current set-up works fine for how I interface with the site, but if it's something worth changing stuff around for I'd be more than happy to!

**Comment by jmkd3v** [comment]
If you leave the uncompiled source on GitHub, it makes it possible for other users to contribute and edit your site through pull requests! I was about to add a small CSS class to your code but I can't because the uncompiled version is not available and what I write will be overwritten as soon as you push from your PC again.

**Comment by MenacingMecha** [comment]
Feel free to submit the PR, nothing will get overwritten - not sure what you mean by compiled vs uncompiled, all the source code is there.

Only thing I can think of is there's a couple of orphaned files from the template this was originally derived from, but they are no longer referred to.
